import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF8E7',
        paddingHorizontal: 24,
        marginTop: 5,
        alignItems: 'center'
    },
    titleContainer: {
        paddingHorizontal: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    title: {
        width: 350,
        fontSize: 26,
        color: '#666',
        fontFamily: 'NeulisSemiBold',
        textAlign: 'center',
        marginBottom: 10,
        marginTop: 25,
        lineHeight: 26,
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 20,
    },
    inputContainer: {
        flexDirection: 'row',
        marginBottom: 15,
        marginTop: 10,
    },
    input: {
        flex: 1,
        height: 50,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        paddingHorizontal: 15,
        fontSize: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    searchButton: {
        marginLeft: 10,
        height: 50,
        width: 50,
        backgroundColor: '#CA1741', 
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
    },
    map: {
        width: '100%',
        height: height * 0.48,
        borderRadius: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        overflow: 'hidden',

        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 4,
    },
    statusMessage: {
        fontSize: 18,
        color: '#333',

        textAlign: 'center',
        marginBottom: 10,
        fontFamily: 'NeulisSemiBold',
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 248, 231, 0.7)',
        zIndex: 10,
    },
});
