import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flexGrow: 1, // Permite scroll se o conteúdo for maior que a tela
        backgroundColor: '#FFF8E7',
        padding: 20,
    },
    title: {
        fontSize: 30,
        color: '#CA1741',
        fontFamily: 'NeulisBold',
        textAlign: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    subtitle: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 30,
        lineHeight: 22,
    },
    inputContainer: {
        marginBottom: 20,
    },
    label: {
        fontSize: 16,
        color: '#333',
        fontFamily: 'NeulisSemiBold',
        marginBottom: 8,
        marginLeft: 4,
    },
    dateButton: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 15,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    calculateButton: {
        backgroundColor: '#CA1741',
        borderRadius: 25,
        paddingVertical: 15,
        alignItems: 'center',
        marginTop: 30,
        shadowColor: 'rgba(118, 36, 27, 1)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    calculateButtonText: {
        fontSize: 18,
        color: '#fff',
        fontFamily: 'NeulisBold',
    },
    resultContainer: {
        marginTop: 40,
        padding: 20,
        backgroundColor: '#fff',
        borderRadius: 15,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#EEE',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    resultTitle: {
        fontSize: 20,
        color: '#333',
        fontFamily: 'NeulisBold',
        marginBottom: 10,
    },
    resultDate: {
        fontSize: 28,
        color: '#31C9EB',
        fontFamily: 'NeulisBold',
        marginBottom: 10,
    },
    resultMessage: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        fontFamily: 'NeulisRegular',
    },
});